### ISSUE TITLE
The warning doesn't fit the page size

### ISSUE THREAD

**Issue by ViniciusPP** [DanzHD/404PageRevival#1]
The warning to check for a saved version on the Internet Archive doesn't fit the screen size in some sites "404 error" page.

Examples:
Google 404 page
![google404](https://github.com/DanzHD/404PageRevival/assets/93277803/19a2c7ec-b142-4ba6-9b0e-ed83409f6c0e)

IMDB 404 page
![imdb404](https://github.com/DanzHD/404PageRevival/assets/93277803/69d1caa4-cedd-4770-8b48-617feca182ec)

Tested only on Firefox.

**Comment by DanzHD** [comment]
Thanks for letting me know. It should be fixed now. Please Let me know if there are any other issues.
